pyms:
  services:
    service_discovery:
      service: "consul"
      host: "localhost"
      autoregister: true
  config:
    DEBUG: true
    TESTING: false
    APP_NAME: "Python Microservice"
    APPLICATION_ROOT: ""